# ============================================================================
# MET VALUES: valores MET por exercício, copiados verbatim de
# GymNight-Desktop/src/database/parser.py (_EXERCISE_MET_MAP).
# ============================================================================
"""
Chaves já normalizadas (lowercase, sem acentos) — casam diretamente com
`seed_helpers.normalize_exercise_name(display_name)`. Exercício sem entrada
aqui simplesmente não ganha linha em `exercise_met_values` (o fallback MET
5.0 é tratado no cálculo de calorias, não no seed).
"""

EXERCISE_MET_MAP: dict[str, float] = {
    # Peito
    "supino reto (barra)": 6.0,
    "supino inclinado (barra)": 6.0,
    "supino declinado (barra)": 6.0,
    "supino com halteres": 6.0,
    "supino inclinado halteres": 6.0,
    "supino declinado halteres": 6.0,
    "crucifixo reto": 6.0,
    "crucifixo inclinado": 6.0,
    "crucifixo declinado": 6.0,
    "voador (pec deck)": 6.0,
    "crossover polia alta": 6.0,
    "crossover polia baixa": 6.0,
    "crossover polia media": 6.0,
    "flexao de braco (push-up)": 7.5,
    "flexao diamante": 7.5,
    "flexao inclinada (maos no banco)": 7.5,
    "flexao declinada (pes no banco)": 7.5,
    "flexao arqueiro": 7.5,
    "flexao explosiva (clap)": 11.0,
    "paralelas (foco peito)": 7.5,
    "pullover (halter)": 6.0,
    "pullover (barra)": 6.0,
    "chest press maquina": 6.0,
    "chest press inclinado maquina": 6.0,
    "floor press (barra)": 6.0,
    "floor press (halteres)": 6.0,
    "svend press": 6.0,
    "landmine press (peito)": 6.0,
    "crucifixo maquina": 6.0,
    "supino pegada invertida": 6.0,
    "supino articulado": 6.0,
    "fly com cabos inclinado": 6.0,
    "flexao com peso (anilha)": 7.5,
    # Costas
    "barra fixa (pronada)": 7.5,
    "barra fixa (supinada/chin-up)": 7.5,
    "barra fixa (neutra)": 7.5,
    "puxada alta (lat pulldown)": 6.0,
    "puxada triangulo": 6.0,
    "puxada supinada": 6.0,
    "puxada por tras": 6.0,
    "remada curvada (barra)": 6.0,
    "remada curvada (supinada)": 6.0,
    "remada unilateral (serrote)": 6.0,
    "remada baixa (polia)": 6.0,
    "remada cavalinho (t-bar)": 6.0,
    "remada cavalinho apoiada": 6.0,
    "pulldown (bracos estendidos)": 6.0,
    "remada articulada": 6.0,
    "remada pendlay": 6.0,
    "remada meadow": 6.0,
    "remada seal (banco alto)": 6.0,
    "remada invertida (calistenia)": 6.0,
    "face pull (foco posterior)": 6.0,
    "levantamento terra (convencional)": 5.0,
    "rack pull": 6.0,
    "hiperextensao lombar": 6.0,
    "bom dia (good morning)": 6.0,
    "superman (isometria)": 6.0,
    "remada alta (pegada larga)": 6.0,
    "puxada unilateral cabo": 6.0,
    "remada com halteres (banco inclinado)": 6.0,
    "remada renegade": 6.0,
    "muscle up (fase puxada)": 7.5,
    "remada t-bar livre": 6.0,
    "puxada com corda": 6.0,
    "remada na maquina hammer": 6.0,
    # Ombros
    "desenvolvimento barra (militar)": 3.5,
    "desenvolvimento halteres": 3.5,
    "desenvolvimento arnold": 3.5,
    "desenvolvimento maquina": 3.5,
    "elevacao lateral (halter)": 3.5,
    "elevacao lateral (polia)": 3.5,
    "elevacao lateral inclinada": 3.5,
    "elevacao frontal (halter)": 3.5,
    "elevacao frontal (barra)": 3.5,
    "elevacao frontal (anilha)": 3.5,
    "crucifixo inverso (halter)": 3.5,
    "crucifixo inverso (maquina)": 3.5,
    "crucifixo inverso (polia)": 3.5,
    "encolhimento (barra)": 3.5,
    "encolhimento (halteres)": 3.5,
    "z-press (sentado no chao)": 3.5,
    "push press": 3.5,
    "bradford press": 3.5,
    'elevacao lateral "y"': 3.5,
    "face pull corda": 3.5,
    "remada alta (barra ez)": 3.5,
    "desenvolvimento por tras": 3.5,
    "pike push-up": 7.5,
    "handstand push-up": 7.5,
    "elevacao lateral unilateral cabo": 3.5,
    "crucifixo inverso unilateral cabo": 3.5,
    "landmine press unilateral": 3.5,
    "snatch grip high pull": 11.0,
    "clean and press": 11.0,
    "thruster": 11.0,
    "elevacao frontal cabo": 3.5,
    "desenvolvimento smith": 3.5,
    "face pull polia alta": 3.5,
    # Bíceps
    "rosca direta (barra)": 3.5,
    "rosca direta (barra ez)": 3.5,
    "rosca martelo": 3.5,
    "rosca scott (barra ez)": 3.5,
    "rosca inclinada (halter)": 3.5,
    "rosca concentrada": 3.5,
    "rosca alternada": 3.5,
    "rosca zottman": 3.5,
    "rosca aranha (spider curl)": 3.5,
    "rosca no cabo (polia baixa)": 3.5,
    "rosca martelo com corda": 3.5,
    "rosca inversa (barra)": 3.5,
    "rosca 21": 3.5,
    "rosca drag": 3.5,
    "rosca hercules (crossover alto)": 3.5,
    "rosca maquina": 3.5,
    "rosca alternada com rotacao": 3.5,
    "rosca direta com halteres": 3.5,
    "rosca martelo inclinada": 3.5,
    "rosca scott unilateral": 3.5,
    "rosca paje (antebraco)": 3.5,
    "flexao de punho": 7.5,
    "extensao de punho": 3.5,
    "rosca direta na polia alta": 3.5,
    "rosca concentrada no cabo": 3.5,
    "rosca martelo alternada": 3.5,
    "rosca direta pegada larga": 3.5,
    "rosca direta pegada estreita": 3.5,
    "rosca scott maquina": 3.5,
    "rosca martelo com halteres": 3.5,
    "rosca direta com anilha": 3.5,
    "rosca martelo com anilha": 3.5,
    "rosca direta com kettlebell": 3.5,
    # Tríceps
    "triceps testa (barra ez)": 3.5,
    "triceps pulley (barra reta)": 3.5,
    "triceps pulley (corda)": 3.5,
    "triceps frances (halter)": 3.5,
    "triceps frances (polia baixa)": 3.5,
    "triceps coice (halter)": 3.5,
    "triceps coice (polia)": 3.5,
    "supino fechado (close grip)": 3.5,
    "mergulho no banco (dips)": 3.5,
    "paralelas (foco triceps)": 7.5,
    "triceps testa (halteres)": 3.5,
    "triceps invertido (polia)": 3.5,
    "triceps unilateral (polia)": 3.5,
    "triceps maquina": 3.5,
    "triceps testa inclinado": 3.5,
    "triceps testa declinado": 3.5,
    "extensao de triceps sobre a cabeca": 3.5,
    "triceps corda unilateral": 3.5,
    "triceps frances com barra ez": 3.5,
    "triceps pulley com barra v": 3.5,
    "triceps coice com halteres": 3.5,
    "triceps testa com kettlebell": 3.5,
    "triceps frances sentado": 3.5,
    "triceps frances em pe": 3.5,
    "triceps pulley pegada invertida": 3.5,
    "triceps testa no cabo": 3.5,
    "triceps frances no cabo": 3.5,
    "triceps coice no cabo": 3.5,
    "triceps maquina sentado": 3.5,
    "triceps mergulho maquina": 3.5,
    "triceps extensao unilateral halter": 3.5,
    "triceps extensao com anilha": 3.5,
    "triceps extensao com elastico": 3.5,
    # Pernas
    "agachamento livre (back squat)": 5.0,
    "agachamento frontal": 5.0,
    "leg press 45": 5.0,
    "hack squat": 5.0,
    "cadeira extensora": 3.5,
    "mesa flexora": 3.5,
    "cadeira flexora": 3.5,
    "stiff (rdl)": 5.0,
    "levantamento terra sumo": 5.0,
    "agachamento bulgaro": 5.0,
    "passada (lunges)": 5.0,
    "elevacao pelvica (hip thrust)": 3.5,
    "panturrilha em pe": 3.5,
    "panturrilha sentado": 3.5,
    "cadeira abdutora": 3.5,
    "cadeira adutora": 3.5,
    "agachamento goblet": 5.0,
    "agachamento sumo (halter)": 5.0,
    "flexor em pe unilateral": 3.5,
    "panturrilha no leg press": 5.0,
    "sissy squat": 3.5,
    "gluteo na polia": 3.5,
    "abducao de quadril polia": 3.5,
    "aducao de quadril polia": 3.5,
    "agachamento smith": 5.0,
    "step up (subida no banco)": 3.5,
    "agachamento cossaco": 5.0,
    "pistol squat": 3.5,
    "flexao nordica": 7.5,
    "extensao de quadril (gluteo maquina)": 3.5,
    # Abdômen
    "abdominal supra": 3.8,
    "abdominal infra": 3.8,
    "prancha isometrica (plank)": 2.8,
    "abdominal roda (ab wheel)": 3.8,
    "elevacao de pernas pendurado": 3.8,
    "russian twist": 3.8,
    "pallof press": 3.8,
    "prancha lateral": 3.8,
    "abdominal obliquo": 3.8,
    "dead bug": 3.8,
    "bird dog": 3.8,
    "abdominal canivete": 3.8,
    "prancha com toque no ombro": 3.8,
    "mountain climbers": 11.0,
    "abdominal bicicleta": 3.8,
}
